# Generated by Django 3.2.5 on 2021-07-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diary/')),
                ('body', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('weather', models.CharField(max_length=100)),
            ],
        ),
    ]
